### ISSUE TITLE
Pokemon Images

### ISSUE THREAD

**Issue by DesmondANIMUS** [DesmondANIMUS/pakdemon#2]
I am fetching a list of pokemon. Please fetch pokemon images and their info for each pokemon. And show their images. 

While I'm fetching pokemon data, I'm getting a link per pokemon so I can fetch more details about them. Looking at json data you should be able to do it. 

If you get stuck due to my spaghetti code then we can talk about it. Will be fun ^.^

**Comment by dbrudner** [comment]
Checking this out!

**Comment by dbrudner** [comment]
https://github.com/DesmondANIMUS/pakdemon/pull/6
