### ISSUE TITLE
Broken API link in app :/

### ISSUE THREAD

**Issue by DesmondANIMUS** [DesmondANIMUS/pakdemon#40]
API url isn't working anymore. Can't figure out what's the issue. Could use some help here!

**Comment by MichaelNZ404** [comment]
The API isn't down but it is super slow for me. I am able to load http://pokeapi.salestock.net/api/v2/ but none of the other pages which would indicate they are having some database troubles.

I would encourage you to create an issue to display some message if the API is unavailable. I would be happy to do this for you in the spirit of pokemon and hacktober :)

**Comment by mikicaivosevic** [comment]
API is super slow definitely, 11s for response.

**Comment by DesmondANIMUS** [comment]
@MichaelNZ404, @mikicaivosevic well I was getting 500 error. And sure, will create an issue for that.
@mikicaivosevic thanks for that PR with new URL.
