### ISSUE TITLE
Take care of security warnings/vulnerable deps ^.^

### ISSUE THREAD

**Issue by DesmondANIMUS** [DesmondANIMUS/pakdemon#46]
Hint for newbies: node audit will help

Edit: **npm** audit

**Comment by minhnhattonthat** [comment]
will work on this 😃

**Comment by DesmondANIMUS** [comment]
I see. Thanks for the fix ^.^

I raised this issue because GitHub warned me about some vulns in some of the dependencies in package-lock.json

**Comment by minhnhattonthat** [comment]
No problem! You can try to do a fresh install again to see if the vulnerabilities still persist.
