### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by akmadhwa** [DesmondANIMUS/pakdemon#49]
I have a problem when the app try to get the data from pokeapi. 

`Access to XMLHttpRequest at 'http://pokeapi.co/api/v2/type/1/' (redirected from 'https://pokeapi.co/api/v2//type/1') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by DesmondANIMUS** [comment]
Ow .-.

Well, the previous link that we were using was too slow. This one has CORS problem. I am not sure what's the alternative. Maybe you can find one?

**Comment by akmadhwa** [comment]
I think the problem is from the API itself. 

what i found from pokeapi issue is you need to add "/" 

https://github.com/PokeAPI/pokeapi/issues/289#issuecomment-375978892

**Comment by akmadhwa** [comment]
#50

**Comment by DesmondANIMUS** [comment]
@akmadhwa ow, well that's a weird fix, but if it works then I guess it's cool

Thank You for your contribution. ^.^
